sudo: required  
dist: trusty
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
before_install:  
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - ls -ltr /home/travis/
script:
  - mvn test -Dwebdriver.chrome.driver=/usr/bin/google-chrome
cache:
  directories:
  - $HOME/.m2