language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
script:
  - mvn test -Dphantomjs.binary.path=phantomjs
cache:
  directories:
  - $HOME/.m2