sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:  
  - export CHROME_BIN=chromium-browser
  - whereis chrome-browser
  - sudo chmod 777 /usr/bin/chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
script:
  - mvn test -Dwebdriver.chrome.driver=/usr/bin/chromium-browser -Ddriver=chrome
cache:
  directories:
  - $HOME/.m2