language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:  
  - export CHROME_BIN=chromium-browser
  - echo $CHROME_BIN
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
script:
  - mvn test -Dwebdriver.chrome.driver=/usr/bin/google-chrome
cache:
  directories:
  - $HOME/.m2