language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
  - echo $HOME
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
script:
  - mvn test -Dwebdriver.gecko.driver=/home/travis/firefox-46.0/firefox
cache:
  directories:
  - $HOME/.m2
addons:
  firefox: "46.0"