language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
script:
  - mvn test -Dwebdriver.gecko.driver=/home/travis/47.0/firefox/firefox
cache:
  directories:
  - $HOME/.m2
addons:
  firefox: "47.0"